# NumPy Crash Course
Notebook adapted from https://github.com/nicknochnack/NumpyCrashCourse

# 0. Installing/Importing

In [13]:
!pip install numpy

In [ ]:
# Creating, Reading, Updating, Deleting NumPy Arrys. [CRUD]

In [40]:
import numpy as np
# Common practice to use shorthand such as np

# 1. Create

In [3]:
# An array is just a list that looks like this [1,2,3,4]
# If we want 2-Dimensional Array then we can have something like this [[1,2,3], [1,2,3]]. Two arrays inside an array

In [4]:
data = np.random.rand(2,3,4) # See how to create randomly genetrated arrays. Shape of 2,3,4
zeroes = np.zeros((2,2,2)) 
full = np.full((2,2,2), 7) 
ones = np.ones((2,2,2))

In [5]:
data #You can see it has got a bunch of random numbers 

array([[[0.93405577, 0.06185959, 0.04562737, 0.23055005],
        [0.41652909, 0.55953698, 0.30060159, 0.45693774],
        [0.42726738, 0.56452185, 0.54517056, 0.01581227]],

       [[0.45628802, 0.01438678, 0.106023  , 0.8927118 ],
        [0.5110844 , 0.39236647, 0.70974741, 0.76707932],
        [0.07630014, 0.92865881, 0.46454512, 0.16692912]]])

In [6]:
zeroes # you can see it has a abunch of zeroes in it 

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [7]:
full  #Instead of having zeros we are replaing them with 7's

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [8]:
ones #Similar to zeros but replaces values with 1's 

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [9]:
# Create an array with our own numbers 
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

# 2. Read

In [12]:
# Attributes
shape = data.shape # get the shape of the array of the data array
size = data.size #size of value in our array 
types = data.dtype # get the type 

In [13]:
types

dtype('float64')

Differnce between List and Array? A list can have mulitple data types while an array only has one data type. List cannot manage airthmetics function while an array can

In [14]:
# Slicing -- say you want to work through different values in our array 
arr = data[0]
slicer = data[0][0:2] #Slicer can be used to get multiple values 
reverse = data[-1]
singleval = data[0][0][0]

In [15]:
singleval

0.9340557737240806

In [16]:
data

array([[[0.93405577, 0.06185959, 0.04562737, 0.23055005],
        [0.41652909, 0.55953698, 0.30060159, 0.45693774],
        [0.42726738, 0.56452185, 0.54517056, 0.01581227]],

       [[0.45628802, 0.01438678, 0.106023  , 0.8927118 ],
        [0.5110844 , 0.39236647, 0.70974741, 0.76707932],
        [0.07630014, 0.92865881, 0.46454512, 0.16692912]]])

In [17]:
data[-1]

array([[0.45628802, 0.01438678, 0.106023  , 0.8927118 ],
       [0.5110844 , 0.39236647, 0.70974741, 0.76707932],
       [0.07630014, 0.92865881, 0.46454512, 0.16692912]])

# 3. Update

In [18]:
list1 = np.random.rand(10) 
list2 = np.random.rand(10) 

In [19]:
list2

array([0.5769215 , 0.55985653, 0.45911246, 0.18719709, 0.44315285,
       0.99202033, 0.82832876, 0.17622163, 0.92879381, 0.13049365])

In [20]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [21]:
add

array([1.46332299, 0.95832451, 1.19134032, 0.91823696, 0.51743655,
       1.17746886, 1.00717322, 0.95732427, 1.36089876, 0.37359773])

In [23]:
# Statistcal Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [24]:
maxs

0.8864014940523551

In [25]:
maxs

0.8864014940523551

In [26]:
data

array([[[0.93405577, 0.06185959, 0.04562737, 0.23055005],
        [0.41652909, 0.55953698, 0.30060159, 0.45693774],
        [0.42726738, 0.56452185, 0.54517056, 0.01581227]],

       [[0.45628802, 0.01438678, 0.106023  , 0.8927118 ],
        [0.5110844 , 0.39236647, 0.70974741, 0.76707932],
        [0.07630014, 0.92865881, 0.46454512, 0.16692912]]])

In [27]:
data[0][0][0] = 700

In [28]:
data

array([[[7.00000000e+02, 6.18595854e-02, 4.56273735e-02, 2.30550047e-01],
        [4.16529094e-01, 5.59536981e-01, 3.00601591e-01, 4.56937739e-01],
        [4.27267378e-01, 5.64521847e-01, 5.45170563e-01, 1.58122745e-02]],

       [[4.56288021e-01, 1.43867804e-02, 1.06022995e-01, 8.92711796e-01],
        [5.11084397e-01, 3.92366473e-01, 7.09747412e-01, 7.67079316e-01],
        [7.63001419e-02, 9.28658805e-01, 4.64545122e-01, 1.66929125e-01]]])

In [29]:
data.sort()
data

array([[[4.56273735e-02, 6.18595854e-02, 2.30550047e-01, 7.00000000e+02],
        [3.00601591e-01, 4.16529094e-01, 4.56937739e-01, 5.59536981e-01],
        [1.58122745e-02, 4.27267378e-01, 5.45170563e-01, 5.64521847e-01]],

       [[1.43867804e-02, 1.06022995e-01, 4.56288021e-01, 8.92711796e-01],
        [3.92366473e-01, 5.11084397e-01, 7.09747412e-01, 7.67079316e-01],
        [7.63001419e-02, 1.66929125e-01, 4.64545122e-01, 9.28658805e-01]]])

In [30]:
print(data.shape)

(2, 3, 4)


In [31]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [32]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [33]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# 4. Delete

In [34]:
data

array([[[4.56273735e-02, 6.18595854e-02, 2.30550047e-01, 7.00000000e+02,
         3.00601591e-01, 4.16529094e-01],
        [4.56937739e-01, 5.59536981e-01, 1.58122745e-02, 4.27267378e-01,
         5.45170563e-01, 5.64521847e-01]],

       [[1.43867804e-02, 1.06022995e-01, 4.56288021e-01, 8.92711796e-01,
         3.92366473e-01, 5.11084397e-01],
        [7.09747412e-01, 7.67079316e-01, 7.63001419e-02, 1.66929125e-01,
         4.64545122e-01, 9.28658805e-01]]])

In [35]:
np.delete(data, 0, axis=1)

array([[[0.45693774, 0.55953698, 0.01581227, 0.42726738, 0.54517056,
         0.56452185]],

       [[0.70974741, 0.76707932, 0.07630014, 0.16692912, 0.46454512,
         0.92865881]]])

In [36]:
np.save("new array", data)

In [37]:
test = np.load("new array.npy")

In [38]:
test

array([[[4.56273735e-02, 6.18595854e-02, 2.30550047e-01, 7.00000000e+02,
         3.00601591e-01, 4.16529094e-01],
        [4.56937739e-01, 5.59536981e-01, 1.58122745e-02, 4.27267378e-01,
         5.45170563e-01, 5.64521847e-01]],

       [[1.43867804e-02, 1.06022995e-01, 4.56288021e-01, 8.92711796e-01,
         3.92366473e-01, 5.11084397e-01],
        [7.09747412e-01, 7.67079316e-01, 7.63001419e-02, 1.66929125e-01,
         4.64545122e-01, 9.28658805e-01]]])

## Exercice 1

Insert the correct syntax for checking the number of dimension of a NumPy array.


arr = np.array([1, 2, 3, 4])

print(arr.___)

## Exercice 2

Insert the correct method for creating a NumPy array.


arr = np.___([1, 2, 3, 4, 5])

## Exercice 3


Insert the correct syntax for printing the first item in the array.


arr = np.array([1, 2, 3, 4, 5])

print(arr___)

## Exercice 4


Insert the correct syntax for printing the number 50 from the array.


arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

print(arr____)

## Exercice 5



Use negative index to print the last item in the array.


arr = np.array([10, 20, 30, 40, 50])

print(arr___)

## Exercice 6



Insert the correct slicing syntax to print the following selection of the array:

Everything from (including) the second item to (not including) the fifth item.


arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr___)

## Exercice 7



Insert the correct slicing syntax to print the following selection of the array:

Everything from (including) the third item to (not including) the fifth item.


arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr___)

## Exercice 8



Insert the correct slicing syntax to print the following selection of the array:

Every other item from (including) the second item to (not including) the fifth item.

Tip: use the step syntax.


arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr____)

## Exercise 9

Insert the correct slicing syntax to print the following selection of the array:

Every other item from the entire array.

Tip: use the step syntax.


arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr____)

## Exercise 10

Insert the correct NumPy syntax to print the data type of an array.


arr = np.array([1, 2, 3, 4])

print(arr.___)

## Exercise 11

Use the correct NumPy method to change the shape of an array from 1-D to 2-D.


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.___(4, 3)

## Exercise 12

Use the correct NumPy method to return a sorted array.


arr = np.array([3, 2, 0, 1])

x = np.___(arr)